const words = [
  { word: "Deception", type: "noun", turkish: "Aldatma, hile", example: "The deception was discovered." },
  { word: "Disperse", type: "verb", turkish: "Dağıtmak, yaymak", example: "The crowd began to disperse." },
  { word: "Grasp", type: "verb", turkish: "Kavramak, anlamak", example: "She couldn't grasp the concept." },
  { word: "Instill", type: "verb", turkish: "Aşılamak, telkin etmek", example: "Parents instill values in children." },
  { word: "Isolate", type: "verb", turkish: "Yalıtmak, ayırmak", example: "They isolated the virus." },
  { word: "Spoil", type: "verb", turkish: "Bozmak, şımartmak", example: "Don't spoil the surprise." },
  { word: "Precipitate", type: "verb", turkish: "Hızlandırmak, tetiklemek", example: "The crisis precipitated change." },
  { word: "Quotation", type: "noun", turkish: "Alıntı, teklif", example: "A famous quotation." },
  { word: "Realm", type: "noun", turkish: "Alan, krallık", example: "In the realm of science." },
  { word: "Migration", type: "noun", turkish: "Göç", example: "Bird migration patterns." },
  { word: "Nullify", type: "verb", turkish: "Geçersiz kılmak", example: "The court nullified the law." },
  { word: "Obesity", type: "noun", turkish: "Obezite, şişmanlık", example: "Obesity is a health issue." },
  { word: "Poison", type: "noun", turkish: "Zehir", example: "The poison was deadly." },
  { word: "Specify", type: "verb", turkish: "Belirtmek, açıklamak", example: "Please specify your needs." },
  { word: "Supplant", type: "verb", turkish: "Yerini almak", example: "Digital supplanted analog." },
  { word: "Dilate", type: "verb", turkish: "Genişlemek, büyümek", example: "Pupils dilate in darkness." },
  { word: "Deal", type: "noun", turkish: "Anlaşma, miktar", example: "We made a deal." },
  { word: "Decade", type: "noun", turkish: "On yıl", example: "The last decade." },
  { word: "Contempt", type: "noun", turkish: "Küçümseme, aşağılama", example: "He showed contempt." },
  { word: "Adjourn", type: "verb", turkish: "Ertelemek", example: "The meeting was adjourned." },
  { word: "Assign", type: "verb", turkish: "Atamak, görevlendirmek", example: "Assign tasks to team." },
  { word: "Track", type: "verb", turkish: "İzlemek, takip etmek", example: "Track your progress." },
  { word: "Treasure", type: "verb", turkish: "Değer vermek", example: "I treasure our friendship." },
  { word: "Threat", type: "noun", turkish: "Tehdit", example: "A serious threat." },
  { word: "Attach", type: "verb", turkish: "Eklemek, iliştirmek", example: "Attach the document." },
  { word: "Attitude", type: "noun", turkish: "Tutum, tavır", example: "Positive attitude matters." },
  { word: "Apathy", type: "noun", turkish: "İlgisizlik, kayıtsızlık", example: "Political apathy is common." },
  { word: "Annihilation", type: "noun", turkish: "Yok etme, imha", example: "Total annihilation." },
  { word: "Consolidate", type: "verb", turkish: "Birleştirmek, sağlamlaştırmak", example: "Consolidate your position." },
  { word: "Coerce", type: "verb", turkish: "Zorlamak, baskı yapmak", example: "Coerce someone into action." },
  { word: "Defect", type: "noun", turkish: "Kusur, hata", example: "A manufacturing defect." },
  { word: "Despise", type: "verb", turkish: "Hor görmek, nefret etmek", example: "I despise dishonesty." },
  { word: "Expend", type: "verb", turkish: "Harcamak, tüketmek", example: "Expend energy wisely." },
  { word: "Entitle", type: "verb", turkish: "Hak vermek, yetkilendirmek", example: "You are entitled to this." },
  { word: "Illustrate", type: "verb", turkish: "Göstermek, resimlemek", example: "Illustrate the concept." },
  { word: "Influx", type: "noun", turkish: "Akın, giriş", example: "An influx of tourists." },
  { word: "Grumble", type: "verb", turkish: "Homurdanmak, şikayet etmek", example: "Don't grumble about it." },
  { word: "Obligation", type: "noun", turkish: "Yükümlülük, zorunluluk", example: "A legal obligation." },
  { word: "Momentum", type: "noun", turkish: "İvme, hız", example: "Gain momentum." },
  { word: "Menace", type: "verb", turkish: "Tehdit etmek", example: "A menace to society." },
  { word: "Negotiate", type: "verb", turkish: "Müzakere etmek, pazarlık yapmak", example: "Negotiate a deal." },
  { word: "Pose", type: "verb", turkish: "Ortaya koymak, poz vermek", example: "Pose a question." },
  { word: "Exaggerate", type: "verb", turkish: "Abartmak", example: "Don't exaggerate the story." },
  { word: "Exhaust", type: "verb", turkish: "Tüketmek, bitkin düşürmek", example: "Exhaust all options." },
  { word: "Discriminate", type: "verb", turkish: "Ayrım yapmak, ayırt etmek", example: "Discriminate between colors." },
  { word: "Dismiss", type: "verb", turkish: "Görevden almak, reddetmek", example: "Dismiss the idea." },
  { word: "Custody", type: "noun", turkish: "Velayet, gözaltı", example: "Child custody case." },
  { word: "Commerce", type: "noun", turkish: "Ticaret", example: "Electronic commerce." },
  { word: "Ambition", type: "noun", turkish: "Hırs, tutku", example: "Political ambition." },
  { word: "Absorb", type: "verb", turkish: "Emmek, özümsemek", example: "Absorb the information." },
  { word: "Abundant", type: "adjective", turkish: "Bol, bereketli", example: "Abundant resources." },
  { word: "Accomplish", type: "verb", turkish: "Başarmak, gerçekleştirmek", example: "Accomplish your goals." },
  { word: "Accumulate", type: "verb", turkish: "Biriktirmek, yığmak", example: "Accumulate wealth." },
  { word: "Accurate", type: "adjective", turkish: "Doğru, kesin", example: "Accurate information." },
  { word: "Acknowledge", type: "verb", turkish: "Kabul etmek, onaylamak", example: "Acknowledge the mistake." },
  { word: "Acquire", type: "verb", turkish: "Edinmek, kazanmak", example: "Acquire new skills." },
  { word: "Advocate", type: "verb", turkish: "Savunmak, desteklemek", example: "Advocate for change." },
  { word: "Alleviate", type: "verb", turkish: "Hafifletmek, azaltmak", example: "Alleviate the pain." },
  { word: "Anticipate", type: "verb", turkish: "Öngörmek, beklemek", example: "Anticipate problems." },
  { word: "Apparent", type: "adjective", turkish: "Açık, belli", example: "It became apparent." },
  { word: "Assert", type: "verb", turkish: "İleri sürmek, iddia etmek", example: "Assert your rights." },
  { word: "Assume", type: "verb", turkish: "Varsaymak, üstlenmek", example: "Assume responsibility." },
  { word: "Cease", type: "verb", turkish: "Durdurmak, sona ermek", example: "Cease operations." },
  { word: "Clarify", type: "verb", turkish: "Açıklamak, netleştirmek", example: "Clarify the issue." },
  { word: "Coincide", type: "verb", turkish: "Denk gelmek, örtüşmek", example: "Our views coincide." },
  { word: "Compensate", type: "verb", turkish: "Telafi etmek, tazmin etmek", example: "Compensate for loss." },
  { word: "Compile", type: "verb", turkish: "Derlemek, toplamak", example: "Compile data." },
  { word: "Comply", type: "verb", turkish: "Uymak, riayet etmek", example: "Comply with rules." },
  { word: "Comprehensive", type: "adjective", turkish: "Kapsamlı, geniş", example: "A comprehensive study." },
  { word: "Compulsory", type: "adjective", turkish: "Zorunlu, mecburi", example: "Compulsory education." },
  { word: "Conceive", type: "verb", turkish: "Tasarlamak, düşünmek", example: "Conceive an idea." },
  { word: "Conclude", type: "verb", turkish: "Sonuçlandırmak, bitirmek", example: "Conclude the meeting." },
  { word: "Conduct", type: "verb", turkish: "Yönetmek, yürütmek", example: "Conduct research." },
  { word: "Confine", type: "verb", turkish: "Sınırlamak, hapsetmek", example: "Confine to the room." },
  { word: "Confirm", type: "verb", turkish: "Onaylamak, doğrulamak", example: "Confirm the booking." },
  { word: "Conflict", type: "noun", turkish: "Çatışma, anlaşmazlık", example: "Armed conflict." },
  { word: "Confront", type: "verb", turkish: "Yüzleşmek, karşı çıkmak", example: "Confront the problem." },
  { word: "Consciously", type: "adverb", turkish: "Bilinçli olarak", example: "Consciously decided." },
  { word: "Consent", type: "noun", turkish: "Onay, rıza", example: "With your consent." },
  { word: "Consequence", type: "noun", turkish: "Sonuç, netice", example: "Face consequences." },
  { word: "Considerable", type: "adjective", turkish: "Önemli, hatırı sayılır", example: "Considerable effort." },
  { word: "Consistent", type: "adjective", turkish: "Tutarlı, istikrarlı", example: "Be consistent." },
  { word: "Constitute", type: "verb", turkish: "Oluşturmak, meydana getirmek", example: "Constitute a majority." },
  { word: "Constrain", type: "verb", turkish: "Kısıtlamak, zorlamak", example: "Constrain behavior." },
  { word: "Construct", type: "verb", turkish: "İnşa etmek, oluşturmak", example: "Construct a building." },
  { word: "Consult", type: "verb", turkish: "Danışmak, görüşmek", example: "Consult a doctor." },
  { word: "Consume", type: "verb", turkish: "Tüketmek", example: "Consume less energy." },
  { word: "Contemplate", type: "verb", turkish: "Düşünmek, tasarlamak", example: "Contemplate the future." },
  { word: "Contribute", type: "verb", turkish: "Katkıda bulunmak", example: "Contribute to society." },
  { word: "Controversy", type: "noun", turkish: "Tartışma, anlaşmazlık", example: "Cause controversy." },
  { word: "Convey", type: "verb", turkish: "İletmek, aktarmak", example: "Convey a message." },
  { word: "Convince", type: "verb", turkish: "İkna etmek", example: "Convince someone." },
  { word: "Crucial", type: "adjective", turkish: "Çok önemli, kritik", example: "A crucial decision." },
  { word: "Decline", type: "verb", turkish: "Azalmak, reddetmek", example: "Sales declined." },
  { word: "Dedicate", type: "verb", turkish: "Adamak, ithaf etmek", example: "Dedicate time." },
  { word: "Deem", type: "verb", turkish: "Saymak, kabul etmek", example: "Deem it necessary." },
  { word: "Deny", type: "verb", turkish: "İnkar etmek, reddetmek", example: "Deny the accusation." },
  { word: "Depict", type: "verb", turkish: "Tasvir etmek, betimlemek", example: "Depict in art." },
  { word: "Derive", type: "verb", turkish: "Türemek, elde etmek", example: "Derive pleasure." },
  { word: "Detect", type: "verb", turkish: "Tespit etmek, saptamak", example: "Detect a problem." },
  { word: "Determine", type: "verb", turkish: "Belirlemek, saptamak", example: "Determine the cause." },
  { word: "Devote", type: "verb", turkish: "Adamak, vakfetmek", example: "Devote time to study." },
  { word: "Diminish", type: "verb", turkish: "Azaltmak, küçültmek", example: "Diminish in value." },
  { word: "Discard", type: "verb", turkish: "Atmak, vazgeçmek", example: "Discard old items." },
  { word: "Disclose", type: "verb", turkish: "Açıklamak, ifşa etmek", example: "Disclose information." },
  { word: "Dispute", type: "noun", turkish: "Anlaşmazlık, tartışma", example: "Settle a dispute." },
  { word: "Distinct", type: "adjective", turkish: "Belirgin, farklı", example: "Distinct features." },
  { word: "Distribute", type: "verb", turkish: "Dağıtmak, yaymak", example: "Distribute evenly." },
  { word: "Diverse", type: "adjective", turkish: "Çeşitli, farklı", example: "Diverse cultures." },
  { word: "Dominate", type: "verb", turkish: "Hakim olmak, egemen olmak", example: "Dominate the market." },
  { word: "Durable", type: "adjective", turkish: "Dayanıklı, kalıcı", example: "Durable material." },
  { word: "Elaborate", type: "verb", turkish: "Detaylandırmak, işlemek", example: "Elaborate on the topic." },
  { word: "Eliminate", type: "verb", turkish: "Ortadan kaldırmak, elemek", example: "Eliminate errors." },
  { word: "Embrace", type: "verb", turkish: "Kucaklamak, benimsemek", example: "Embrace change." },
  { word: "Emerge", type: "verb", turkish: "Ortaya çıkmak, belirmek", example: "Emerge as leader." },
  { word: "Emphasize", type: "verb", turkish: "Vurgulamak", example: "Emphasize importance." },
  { word: "Enable", type: "verb", turkish: "Olanak sağlamak, mümkün kılmak", example: "Enable access." },
  { word: "Encounter", type: "verb", turkish: "Karşılaşmak, rastlamak", example: "Encounter problems." },
  { word: "Endure", type: "verb", turkish: "Dayanmak, katlanmak", example: "Endure hardship." },
  { word: "Enhance", type: "verb", turkish: "Artırmak, geliştirmek", example: "Enhance quality." },
  { word: "Ensure", type: "verb", turkish: "Sağlamak, garantilemek", example: "Ensure safety." },
  { word: "Equivalent", type: "adjective", turkish: "Eşdeğer, denk", example: "Equivalent value." },
  { word: "Erode", type: "verb", turkish: "Aşındırmak, yıpratmak", example: "Erode trust." },
  { word: "Establish", type: "verb", turkish: "Kurmak, oluşturmak", example: "Establish a company." },
  { word: "Evaluate", type: "verb", turkish: "Değerlendirmek", example: "Evaluate performance." },
  { word: "Evident", type: "adjective", turkish: "Açık, belli", example: "It was evident." },
  { word: "Evolve", type: "verb", turkish: "Evrimleşmek, gelişmek", example: "Species evolve." },
  { word: "Exceed", type: "verb", turkish: "Aşmak, geçmek", example: "Exceed expectations." },
  { word: "Exclude", type: "verb", turkish: "Hariç tutmak, dışlamak", example: "Exclude from list." },
  { word: "Exhibit", type: "verb", turkish: "Sergilemek, göstermek", example: "Exhibit artwork." },
  { word: "Expand", type: "verb", turkish: "Genişletmek, büyütmek", example: "Expand business." },
  { word: "Exploit", type: "verb", turkish: "Sömürmek, kullanmak", example: "Exploit resources." },
  { word: "Expose", type: "verb", turkish: "Ortaya çıkarmak, maruz bırakmak", example: "Expose the truth." },
  { word: "Extend", type: "verb", turkish: "Uzatmak, genişletmek", example: "Extend deadline." },
  { word: "Extract", type: "verb", turkish: "Çıkarmak, özütlemek", example: "Extract data." },
  { word: "Facilitate", type: "verb", turkish: "Kolaylaştırmak", example: "Facilitate learning." },
  { word: "Feasible", type: "adjective", turkish: "Uygulanabilir, mümkün", example: "A feasible plan." },
  { word: "Fluctuate", type: "verb", turkish: "Dalgalanmak, değişmek", example: "Prices fluctuate." },
  { word: "Formulate", type: "verb", turkish: "Formüle etmek, oluşturmak", example: "Formulate a plan." },
  { word: "Foster", type: "verb", turkish: "Teşvik etmek, beslemek", example: "Foster creativity." },
  { word: "Generate", type: "verb", turkish: "Üretmek, oluşturmak", example: "Generate income." },
  { word: "Genuine", type: "adjective", turkish: "Gerçek, samimi", example: "Genuine concern." },
  { word: "Grant", type: "verb", turkish: "Vermek, bağışlamak", example: "Grant permission." },
  { word: "Hence", type: "adverb", turkish: "Bu nedenle, dolayısıyla", example: "Hence the problem." },
  { word: "Hierarchy", type: "noun", turkish: "Hiyerarşi, sıradüzen", example: "Social hierarchy." },
  { word: "Hypothesis", type: "noun", turkish: "Hipotez, varsayım", example: "Test the hypothesis." },
  { word: "Identical", type: "adjective", turkish: "Aynı, özdeş", example: "Identical twins." },
  { word: "Ignorant", type: "adjective", turkish: "Cahil, bilgisiz", example: "Ignorant of facts." },
  { word: "Imply", type: "verb", turkish: "İma etmek, demek istemek", example: "Imply something." },
  { word: "Impose", type: "verb", turkish: "Dayatmak, yüklemek", example: "Impose restrictions." },
  { word: "Incentive", type: "noun", turkish: "Teşvik, özendirme", example: "Financial incentive." },
  { word: "Incline", type: "verb", turkish: "Eğilim göstermek, meyletmek", example: "Inclined to agree." },
  { word: "Incorporate", type: "verb", turkish: "Dahil etmek, birleştirmek", example: "Incorporate changes." },
  { word: "Indicate", type: "verb", turkish: "Göstermek, belirtmek", example: "Indicate progress." },
  { word: "Induce", type: "verb", turkish: "Neden olmak, teşvik etmek", example: "Induce sleep." },
  { word: "Inevitable", type: "adjective", turkish: "Kaçınılmaz", example: "Inevitable outcome." },
  { word: "Infer", type: "verb", turkish: "Çıkarım yapmak, sonuç çıkarmak", example: "Infer from data." },
  { word: "Inherent", type: "adjective", turkish: "Doğal, yapısal", example: "Inherent risk." },
  { word: "Inhibit", type: "verb", turkish: "Engellemek, durdurmak", example: "Inhibit growth." },
  { word: "Initiate", type: "verb", turkish: "Başlatmak", example: "Initiate a project." },
  { word: "Innovate", type: "verb", turkish: "Yenilik yapmak", example: "Innovate constantly." },
  { word: "Insight", type: "noun", turkish: "İçgörü, kavrayış", example: "Valuable insight." },
  { word: "Integrate", type: "verb", turkish: "Bütünleştirmek, entegre etmek", example: "Integrate systems." },
  { word: "Intensify", type: "verb", turkish: "Yoğunlaştırmak, artırmak", example: "Intensify efforts." },
  { word: "Interpret", type: "verb", turkish: "Yorumlamak, tercüme etmek", example: "Interpret data." },
  { word: "Intervene", type: "verb", turkish: "Müdahale etmek, araya girmek", example: "Intervene in conflict." },
  { word: "Intrinsic", type: "adjective", turkish: "Özsel, doğal", example: "Intrinsic value." },
  { word: "Invoke", type: "verb", turkish: "Başvurmak, çağırmak", example: "Invoke the law." },
  { word: "Legitimate", type: "adjective", turkish: "Meşru, yasal", example: "Legitimate concern." },
  { word: "Liable", type: "adjective", turkish: "Sorumlu, yükümlü", example: "Liable for damage." },
  { word: "Maintain", type: "verb", turkish: "Sürdürmak, korumak", example: "Maintain quality." },
  { word: "Manifest", type: "verb", turkish: "Ortaya koymak, göstermek", example: "Manifest symptoms." },
  { word: "Manipulate", type: "verb", turkish: "Manipüle etmek, kullanmak", example: "Manipulate data." },
  { word: "Mature", type: "adjective", turkish: "Olgun, yetişkin", example: "Mature behavior." },
  { word: "Maximize", type: "verb", turkish: "Maksimize etmek, en üst düzeye çıkarmak", example: "Maximize profit." },
  { word: "Minimize", type: "verb", turkish: "Minimize etmek, en aza indirmek", example: "Minimize risk." },
  { word: "Modify", type: "verb", turkish: "Değiştirmek, düzenlemek", example: "Modify the plan." },
  { word: "Monitor", type: "verb", turkish: "İzlemek, denetlemek", example: "Monitor progress." },
  { word: "Neglect", type: "verb", turkish: "İhmal etmek", example: "Neglect duties." },
  { word: "Nonetheless", type: "adverb", turkish: "Yine de, buna rağmen", example: "Nonetheless, we tried." },
  { word: "Notion", type: "noun", turkish: "Kavram, fikir", example: "A strange notion." },
  { word: "Obtain", type: "verb", turkish: "Elde etmek, edinmek", example: "Obtain permission." },
  { word: "Obvious", type: "adjective", turkish: "Açık, belli", example: "Obvious mistake." },
  { word: "Occupy", type: "verb", turkish: "İşgal etmek, meşgul etmek", example: "Occupy space." },
  { word: "Occur", type: "verb", turkish: "Meydana gelmek, olmak", example: "Accidents occur." },
  { word: "Overlook", type: "verb", turkish: "Gözden kaçırmak, görmezden gelmek", example: "Overlook details." },
  { word: "Perceive", type: "verb", turkish: "Algılamak, fark etmek", example: "Perceive danger." },
  { word: "Persist", type: "verb", turkish: "Sürdürmek, direnmek", example: "Persist in efforts." },
  { word: "Perspective", type: "noun", turkish: "Bakış açısı, perspektif", example: "Different perspective." },
  { word: "Pertain", type: "verb", turkish: "Ait olmak, ilgili olmak", example: "Pertain to the case." },
  { word: "Phenomenon", type: "noun", turkish: "Fenomen, olgu", example: "Natural phenomenon." },
  { word: "Potential", type: "adjective", turkish: "Potansiyel, olası", example: "Potential risk." },
  { word: "Precede", type: "verb", turkish: "Önce gelmek, öncelemek", example: "Precede the event." },
  { word: "Precise", type: "adjective", turkish: "Kesin, tam", example: "Precise measurements." },
  { word: "Predict", type: "verb", turkish: "Tahmin etmek, öngörmek", example: "Predict the future." },
  { word: "Predominant", type: "adjective", turkish: "Baskın, hakim", example: "Predominant view." },
  { word: "Preliminary", type: "adjective", turkish: "Ön, başlangıç", example: "Preliminary results." },
  { word: "Presume", type: "verb", turkish: "Varsaymak, farzetmek", example: "Presume innocence." },
  { word: "Prevail", type: "verb", turkish: "Galip gelmek, hakim olmak", example: "Truth will prevail." },
  { word: "Previous", type: "adjective", turkish: "Önceki, evvelki", example: "Previous experience." },
  { word: "Primarily", type: "adverb", turkish: "Esas olarak, öncelikle", example: "Primarily focused." },
  { word: "Principle", type: "noun", turkish: "İlke, prensip", example: "Basic principle." },
  { word: "Priority", type: "noun", turkish: "Öncelik", example: "Top priority." },
  { word: "Proceed", type: "verb", turkish: "Devam etmek, ilerlemek", example: "Proceed with caution." },
  { word: "Prohibit", type: "verb", turkish: "Yasaklamak", example: "Prohibit smoking." },
  { word: "Prominent", type: "adjective", turkish: "Önemli, belirgin", example: "Prominent figure." },
  { word: "Promote", type: "verb", turkish: "Teşvik etmek, yükseltmek", example: "Promote health." },
  { word: "Proportion", type: "noun", turkish: "Oran, orantı", example: "In proportion." },
  { word: "Prospect", type: "noun", turkish: "Olasılık, beklenti", example: "Future prospects." },
  { word: "Pursue", type: "verb", turkish: "Peşinden gitmek, sürdürmek", example: "Pursue a career." },
  { word: "Range", type: "noun", turkish: "Aralık, menzil", example: "Wide range." },
  { word: "Ratio", type: "noun", turkish: "Oran, rasyo", example: "High ratio." },
  { word: "React", type: "verb", turkish: "Tepki göstermek, reaksiyon vermek", example: "React to news." },
  { word: "Recover", type: "verb", turkish: "İyileşmek, geri kazanmak", example: "Recover quickly." },
  { word: "Refine", type: "verb", turkish: "Rafine etmek, geliştirmek", example: "Refine the process." },
  { word: "Regulate", type: "verb", turkish: "Düzenlemek, regüle etmek", example: "Regulate temperature." },
  { word: "Reinforce", type: "verb", turkish: "Güçlendirmek, pekiştirmek", example: "Reinforce learning." },
  { word: "Reject", type: "verb", turkish: "Reddetmek", example: "Reject the offer." },
  { word: "Relevant", type: "adjective", turkish: "İlgili, alakalı", example: "Relevant information." },
  { word: "Reliable", type: "adjective", turkish: "Güvenilir", example: "Reliable source." },
  { word: "Rely", type: "verb", turkish: "Güvenmek, bağımlı olmak", example: "Rely on data." },
  { word: "Reluctant", type: "adjective", turkish: "İsteksiz, gönülsüz", example: "Reluctant to change." },
  { word: "Remark", type: "verb", turkish: "Söylemek, belirtmek", example: "Remark on the issue." },
  { word: "Remedy", type: "noun", turkish: "Çare, ilaç", example: "Find a remedy." },
  { word: "Remove", type: "verb", turkish: "Kaldırmak, çıkarmak", example: "Remove obstacles." },
  { word: "Require", type: "verb", turkish: "Gerektirmek, istemek", example: "Require attention." },
  { word: "Resemble", type: "verb", turkish: "Benzemek, andırmak", example: "Resemble each other." },
  { word: "Reside", type: "verb", turkish: "İkamet etmek, oturmak", example: "Reside in the city." },
  { word: "Resolve", type: "verb", turkish: "Çözmek, karar vermek", example: "Resolve conflicts." },
  { word: "Restrain", type: "verb", turkish: "Sınırlamak, tutmak", example: "Restrain emotions." },
  { word: "Restrict", type: "verb", turkish: "Kısıtlamak, sınırlamak", example: "Restrict access." },
  { word: "Retain", type: "verb", turkish: "Tutmak, korumak", example: "Retain information." },
  { word: "Reveal", type: "verb", turkish: "Ortaya çıkarmak, açıklamak", example: "Reveal the truth." },
  { word: "Revenue", type: "noun", turkish: "Gelir, hasılat", example: "Increase revenue." },
  { word: "Reverse", type: "verb", turkish: "Tersine çevirmek, geri almak", example: "Reverse the decision." },
  { word: "Revise", type: "verb", turkish: "Gözden geçirmek, revize etmek", example: "Revise the plan." },
  { word: "Rigid", type: "adjective", turkish: "Katı, sert", example: "Rigid rules." },
  { word: "Robust", type: "adjective", turkish: "Sağlam, güçlü", example: "Robust system." },
  { word: "Scope", type: "noun", turkish: "Kapsam, alan", example: "Wide scope." },
  { word: "Secure", type: "verb", turkish: "Güvence altına almak, elde etmek", example: "Secure funding." },
  { word: "Seek", type: "verb", turkish: "Aramak, talep etmek", example: "Seek advice." },
  { word: "Shift", type: "verb", turkish: "Değiştirmek, kaydırmak", example: "Shift focus." },
  { word: "Significant", type: "adjective", turkish: "Önemli, anlamlı", example: "Significant change." },
  { word: "Similar", type: "adjective", turkish: "Benzer", example: "Similar ideas." },
  { word: "Simultaneous", type: "adjective", turkish: "Eş zamanlı", example: "Simultaneous events." },
  { word: "Solely", type: "adverb", turkish: "Yalnızca, sadece", example: "Solely responsible." },
  { word: "Somewhat", type: "adverb", turkish: "Biraz, bir dereceye kadar", example: "Somewhat different." },
  { word: "Sophisticated", type: "adjective", turkish: "Sofistike, karmaşık", example: "Sophisticated technology." },
  { word: "Stable", type: "adjective", turkish: "İstikrarlı, kararlı", example: "Stable economy." },
  { word: "Statistics", type: "noun", turkish: "İstatistik", example: "Crime statistics." },
  { word: "Stimulate", type: "verb", turkish: "Uyarmak, teşvik etmek", example: "Stimulate growth." },
  { word: "Strategy", type: "noun", turkish: "Strateji", example: "Marketing strategy." },
  { word: "Stress", type: "verb", turkish: "Vurgulamak, stres yapmak", example: "Stress importance." },
  { word: "Structure", type: "noun", turkish: "Yapı, strüktür", example: "Organizational structure." },
  { word: "Submit", type: "verb", turkish: "Sunmak, teslim olmak", example: "Submit the report." },
  { word: "Subordinate", type: "adjective", turkish: "Alt, tabi", example: "Subordinate role." },
  { word: "Subsequent", type: "adjective", turkish: "Sonraki, müteakip", example: "Subsequent events." },
  { word: "Substantial", type: "adjective", turkish: "Önemli, hatırı sayılır", example: "Substantial amount." },
  { word: "Substitute", type: "verb", turkish: "Yerine koymak, ikame etmek", example: "Substitute ingredients." },
  { word: "Subtle", type: "adjective", turkish: "İnce, belirsiz", example: "Subtle difference." },
  { word: "Sufficient", type: "adjective", turkish: "Yeterli", example: "Sufficient evidence." },
  { word: "Summarize", type: "verb", turkish: "Özetlemek", example: "Summarize the main points." },
  { word: "Supplement", type: "verb", turkish: "Tamamlamak, eklemek", example: "Supplement income." },
  { word: "Suppress", type: "verb", turkish: "Bastırmak, engellemek", example: "Suppress emotions." },
  { word: "Surplus", type: "noun", turkish: "Fazlalık, artık", example: "Budget surplus." },
  { word: "Survey", type: "noun", turkish: "Anket, inceleme", example: "Conduct a survey." },
  { word: "Survive", type: "verb", turkish: "Hayatta kalmak", example: "Survive the crisis." },
  { word: "Suspend", type: "verb", turkish: "Askıya almak, ertelemek", example: "Suspend operations." },
  { word: "Sustain", type: "verb", turkish: "Sürdürmek, desteklemek", example: "Sustain growth." },
  { word: "Symbol", type: "noun", turkish: "Sembol, simge", example: "National symbol." },
  { word: "Target", type: "noun", turkish: "Hedef", example: "Reach the target." },
  { word: "Task", type: "noun", turkish: "Görev, iş", example: "Complete the task." },
  { word: "Technique", type: "noun", turkish: "Teknik, yöntem", example: "Modern techniques." },
  { word: "Temporary", type: "adjective", turkish: "Geçici", example: "Temporary solution." },
  { word: "Tend", type: "verb", turkish: "Eğiliminde olmak, bakmak", example: "Tend to agree." },
  { word: "Terminate", type: "verb", turkish: "Sona erdirmek, bitirmek", example: "Terminate the contract." },
  { word: "Theory", type: "noun", turkish: "Teori, kuram", example: "Scientific theory." },
  { word: "Thereby", type: "adverb", turkish: "Bu şekilde, böylece", example: "Thereby reducing costs." },
  { word: "Thorough", type: "adjective", turkish: "Kapsamlı, titiz", example: "Thorough investigation." },
  { word: "Trace", type: "verb", turkish: "İzlemek, izini sürmek", example: "Trace the origin." },
  { word: "Tradition", type: "noun", turkish: "Gelenek", example: "Cultural tradition." },
  { word: "Transform", type: "verb", turkish: "Dönüştürmek, değiştirmek", example: "Transform the industry." },
  { word: "Transition", type: "noun", turkish: "Geçiş", example: "Smooth transition." },
  { word: "Transmit", type: "verb", turkish: "İletmek, aktarmak", example: "Transmit data." },
  { word: "Transport", type: "verb", turkish: "Taşımak, nakletmek", example: "Transport goods." },
  { word: "Trigger", type: "verb", turkish: "Tetiklemek, harekete geçirmek", example: "Trigger a reaction." },
  { word: "Ultimate", type: "adjective", turkish: "Son, nihai", example: "Ultimate goal." },
  { word: "Undergo", type: "verb", turkish: "Geçirmek, maruz kalmak", example: "Undergo surgery." },
  { word: "Underlie", type: "verb", turkish: "Altında yatmak, temel oluşturmak", example: "Underlie the theory." },
  { word: "Undertake", type: "verb", turkish: "Üstlenmek, girişmek", example: "Undertake a project." },
  { word: "Uniform", type: "adjective", turkish: "Tek tip, düzgün", example: "Uniform standards." },
  { word: "Unique", type: "adjective", turkish: "Benzersiz, eşsiz", example: "Unique opportunity." },
  { word: "Utilize", type: "verb", turkish: "Kullanmak, yararlanmak", example: "Utilize resources." },
  { word: "Valid", type: "adjective", turkish: "Geçerli", example: "Valid argument." },
  { word: "Variable", type: "adjective", turkish: "Değişken", example: "Variable conditions." },
  { word: "Vary", type: "verb", turkish: "Değişmek, farklılık göstermek", example: "Vary in size." },
  { word: "Vast", type: "adjective", turkish: "Geniş, engin", example: "Vast area." },
  { word: "Verify", type: "verb", turkish: "Doğrulamak, onaylamak", example: "Verify information." },
  { word: "Version", type: "noun", turkish: "Versiyon, sürüm", example: "Latest version." },
  { word: "Violate", type: "verb", turkish: "İhlal etmek, çiğnemek", example: "Violate rules." },
  { word: "Virtual", type: "adjective", turkish: "Sanal", example: "Virtual reality." },
  { word: "Visible", type: "adjective", turkish: "Görünür", example: "Clearly visible." },
  { word: "Volume", type: "noun", turkish: "Hacim, cilt", example: "High volume." },
  { word: "Voluntary", type: "adjective", turkish: "Gönüllü, isteğe bağlı", example: "Voluntary work." },
  { word: "Welfare", type: "noun", turkish: "Refah, iyilik hali", example: "Child welfare." },
  { word: "Whereas", type: "conjunction", turkish: "Oysa, halbuki", example: "Whereas others disagree." },
  { word: "Widespread", type: "adjective", turkish: "Yaygın", example: "Widespread use." },
  { word: "Withdraw", type: "verb", turkish: "Geri çekmek, çekilmek", example: "Withdraw money." },
  { word: "Yield", type: "verb", turkish: "Vermek, boyun eğmek", example: "Yield results." }
];
